services: mongodb

language: ruby

matrix:
  include:
    - rvm: 2.5.0
      env:
        - MONGOID_VERSION=HEAD
    - rvm: 2.5.0
      env:
        - MONGOID_VERSION=7
    - rvm: 2.5.0
      env:
        - MONGOID_VERSION=6
    - rvm: 2.4.0
      env:
        - MONGOID_VERSION=6
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=6
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=5
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=4
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=3
    - rvm: 2.3.0
      before_script:
        - bundle exec danger
  allow_failures:
    - rvm: 2.5.0
      env:
        - MONGOID_VERSION=HEAD

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

before_install:
  - gem update --system
  - gem update bundler
